---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sep-backend-loki-conf
  namespace: singouins
data:
  loki-conf: |
    auth_enabled: false

    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3100
      grpc_listen_address: 0.0.0.0
      grpc_listen_port: 9096

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    compactor:
      retention_enabled: true
      shared_store: filesystem
      working_directory: /loki/compactor

    ruler:
      alertmanager_url: http://localhost:9093
