apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: singouins
  name: sep-backend-loki
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}
