apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-databases
  name: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backup # For promtail logging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: backup # For promtail logging
    spec:
      restartPolicy: Always

      containers:
      - name: backup
        image: lordslair/easydbbackup:1.8.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 16Mi
            cpu: 10m
        env:
          # RCLONE specifics (remote)
          - name: RCLONE_REMOTE_TYPE
            value: 's3'
          - name: RCLONE_REMOTE_PATH
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-remote-path
          # RCLONE specifics (auth)
          - name: RCLONE_CONFIG_S3BACKUP_TYPE
            value: 's3'
          - name: RCLONE_CONFIG_S3BACKUP_ENV_AUTH
            value: 'false'
          - name: RCLONE_CONFIG_S3BACKUP_PROVIDER
            value: 'Other'
          - name: RCLONE_CONFIG_S3BACKUP_ACL
            value: 'private'
          - name: RCLONE_CONFIG_S3BACKUP_ENDPOINT
            value: 'https://s3.waw.io.cloud.ovh.net'
          - name: RCLONE_CONFIG_S3BACKUP_REGION
            value: 'waw'
          - name: RCLONE_CONFIG_S3BACKUP_LOCATION_CONSTRAINT
            value: 'waw'
          - name: RCLONE_CONFIG_S3BACKUP_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-remote-s3-access-key
          - name: RCLONE_CONFIG_S3BACKUP_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-remote-s3-secret-key

          # MONGODB specifics
          - name: MONGODB_DUMP
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mongodb-dump
          - name: MONGODB_EXPORT
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mongodb-export
          - name: MONGO_DB_LIST
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mongodb-dblist
          - name: MONGO_DB_HOST
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mongodb-host
          - name: MONGO_DB_USER
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mongodb-user
          - name: MONGO_DB_PASS
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mongodb-pass

          # MYSQL specifics
          - name: MYSQL_DUMP
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mysql-dump
          - name: MYSQL_DB_LIST
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mysql-dblist
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-host
          - name: MYSQL_DB_PORT
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-port
          - name: MYSQL_DB_PASS
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mysql-pass
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-mysql-user

          # REDIS specifics
          - name: REDIS_DUMP
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-redis-dump
          - name: REDIS_DB_HOST
            value: 'redis-svc.singouins-databases'

          # OUTPUT specifics
          - name: LOG_INFO
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-log-info
          - name: LOG_DATE
            valueFrom:
              secretKeyRef:
                name: backup-secret
                key: backup-log-date
