apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-filestash-secret
type: Opaque
stringData:
  domain: filestash.domain.tld
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-backup-secret
type: Opaque
stringData:
  dblist: "XX,YY"
  pcstype: 'swift'
  pcsenvauth: 'false'
  pcsauthversion: '3'
  pcstenant: <pcstenant>
  pcstenantdomain: 'default'
  pcsdomain: 'default'
  pcsauth: <pcsauth>
  pcsuser: <pcsuser>
  pcskey: <pcskey>
  pcsregion: <pcsregion>
  pcsdir: <pcsdir>
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-mariadb-secret
type: Opaque
stringData:
  user: 'root'
  pass: 'MyMariaDBRootPass'
  port: '3306'
  host: 'my-mariadb-svc'
  exporter-dsn: 'MyMariaDBExporterUser:MyMariaDBExporterPass@(localhost:3306)/'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-metrics-secret
type: Opaque
stringData:
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  sql-host: '<SECRET>'
  sql-db:   '<SECRET>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-api-secret
type: Opaque
stringData:
  jwt-secret: '<JWT-SECRET-PROD>'
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  sql-db: '<SECRET>'
  api-url: '<apiurl>'
  apiproto-url: '<apiprotourl>'
  ldp-host: '<ldphost>'
  ldp-token: '<ldptoken>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-smtp-secret
type: Opaque
stringData:
  smtp-from: '<smtp-from>'
  smtp-server: '<smtp-server>'
  smtp-user: '<smtp-user>'
  smtp-pass: '<smtp-pass>'
  smtp-host: '<smtp-host>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-proto-api-secret
type: Opaque
stringData:
  jwt-secret: '<JWT-SECRET-PROTO>'
  sql-user: 'proto'
  sql-pass: '<protopass>'
  sql-db: 'proto'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-discord-secret
type: Opaque
stringData:
  token-babi:  '<token-babi>'
  token-hapi:  '<token-hapi>'
  invite-url:  '<invite-url>'
  admin-token: '<admin-token>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-wikijs-secret
type: Opaque
stringData:
  dbtype: '<dbtype>'
  dbhost: '<dbhost>'
  dbname: '<dbname>'
  dbuser: '<dbuser>'
  dbpass: '<dbpass>'
  ssl: '<ssl>'
  ha: '<ha>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-angular-secret
type: Opaque
stringData:
  gitrepo: '<remoteuser/repo>'
  gituser: '<gituser>'
  gittoken: '<gittoken>'
  quiet: '<True|False>'
  outputpath: '<outputpath>'
  outputfolderproto: '<outputfolderproto>'
  outputfolderprod: '<outputfolderprod>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-pcs-secret
type: Opaque
stringData:
  pcs-url-public: <pcs-url-public>
