apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-monitoring
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana # For promtail logging
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
        prometheus.io/path: "/metrics"
      labels:
        name: grafana # For promtail logging
    spec:

      containers:
        - name: grafana
          image: grafana/grafana:9.5.12
          resources:
            limits:
              memory: 128Mi
              cpu: 50m
            requests:
              memory: 32Mi
              cpu: 10m
          env:
            - name: GF_DATABASE_TYPE
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-db-type
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-db-host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-db-port
            - name: GF_DATABASE_HOST
              value: "$(DATABASE_HOST):$(DATABASE_PORT)"
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-db-user
            - name: GF_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-db-base
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-db-pass
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-admin-pass
---
apiVersion: v1
kind: Service

metadata:
  namespace: singouins-monitoring
  name: grafana-svc
spec:
  selector:
    name: grafana # For promtail logging
  ports:
  - name: http-grafana
    protocol: TCP
    port: 3000
    targetPort: 3000