apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-prod
  name: resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resolver # For promtail logging
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "5000"
      labels:
        name: resolver # For promtail logging
    spec:
      restartPolicy: Always

      containers:
      - name: resolver
        image: singouins/resolver:attack-algo
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        env:
        # Node env vars
        - name: NODE_ENV
          value: 'dev'
        # App variables
        - name: SEP_API_URL
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-external-url
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-internal-host
        - name: API_PORT
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-internal-port
        # Redis-API variables
        - name: REDISAPI_HOST
          value: 'redis-api-svc.singouins-databases'
        - name: REDISAPI_PORT
          value: '5000'
        # Network
        ports:
        - name: resolver
          containerPort: 3000
        # Healthcheck
        #livenessProbe:
        #    httpGet:
        #      path: /check
        #      port: 3000
        #    initialDelaySeconds: 10
        #    timeoutSeconds: 5
---
apiVersion: v1
kind: Service

metadata:
  namespace: singouins-prod
  name: resolver-svc
spec:
  selector:
    name: resolver # For promtail logging
  ports:
  - name: resolver
    protocol: TCP
    port: 3000