apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis-commander
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-commander # For promtail logging
      tier: sep-backend
  template:
    metadata:
      labels:
        name: redis-commander # For promtail logging
        tier: sep-backend
    spec:

      containers:
      - name: sep-backend-redis-commander
        image: rediscommander/redis-commander:latest
        command: ["./bin/redis-commander.js"]
        args:
          - --redis-host=sep-backend-redis-svc
          - --redis-port=6379
          - --redis-db=0
          - --redis-label=PROD
          - --noload
          - --nosave
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 10m
        # Network
        ports:
        - name: redis-commander
          containerPort: 8081
        # Healthcheck
        livenessProbe:
            httpGet:
              path: /favicon.png
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
