apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-redis-commander-svc
spec:
  selector:
    name: redis-commander # For promtail logging
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: redis-commander
