apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis-api
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-api # For promtail logging
      tier: sep-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        name: redis-api # For promtail logging
        tier: sep-backend
    spec:

      containers:
      - name: sep-backend-redis-api
        image: lordslair/redis-rest-api:v1.2.0
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
        env:
        #  Flask variables
        - name: FLASK_DEBUG
          value: 'False'
        - name: CODE_ENOTFOUND
          value: '200'
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-internal-token
        # Python env vars
        - name: PYTHONUNBUFFERED
          value: 'True'
        - name: PYTHONIOENCODING
          value: 'UTF-8'
        # Loguru env vars
        - name: LOGURU_FORMAT
          value: '<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>level={level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
        - name: LOGURU_COLORIZE
          value: 'true'
        - name: LOGURU_DEBUG_COLOR
          value: '<cyan><bold>'
        - name: LOGURU_LEVEL
          value: 'TRACE'
        # Other env vars
        - name: TZ
          value: 'Europe/Paris'
        # Network
        ports:
        - name: redis-api
          containerPort: 5000
        # Healthcheck
        livenessProbe:
            httpGet:
              path: /check
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 60
