apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis-api
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-api # For promtail logging
      tier: sep-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "5000"
      labels:
        name: redis-api # For promtail logging
        tier: sep-backend
    spec:

      containers:
      - name: sep-backend-redis-api
        image: lordslair/redis-rest-api:latest
        env:
        #  Flask variables
        - name: FLASK_DEBUG
          value: 'False'
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-internal-token
        # Network
        ports:
        - name: redis-api
          containerPort: 5000
        # Healthcheck
        livenessProbe:
            httpGet:
              path: /check
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 60
