apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-redis-api-svc
spec:
  selector:
    name: redis-api # For promtail logging
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: redis-api
