apiVersion: apps/v1
kind: Deployment
metadata:
  name: sep-backend-prometheus
  namespace: singouins
  labels:
    tier: sep-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: prometheus # For promtail logging
      tier: sep-backend
  template:
    metadata:
      labels:
        name: prometheus # For promtail logging
        tier: sep-backend
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: sep-backend-prometheus-data-permission-setup
        image: busybox
        command: ["/bin/chown","-R","65534:65534","/prometheus"]
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus

      containers:
        - name: sep-backend-prometheus
          image: prom/prometheus:v2.44.0
          resources:
            limits:
              memory: 1024Mi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 100m
          args:
            - "--web.listen-address=:9090"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.size=$(RETENTION_SIZE)"
#            - "--storage.tsdb.retention.time=365d"
          env:
          - name: RETENTION_SIZE
            valueFrom:
              secretKeyRef:
                name: sep-backend-prometheus-secret
                key: prometheus-retention-size
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus

      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: sep-backend-prometheus
