{
 "title": "App | Flask (API) Dashboard [PROTO]",
 "tags": [
  "Flask",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "MEM / CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"proto-api\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "gauge",
   "description": "API MEM Usage / ALL MEM Usage",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{app=\"proto-api\"}) / sum(container_memory_working_set_bytes{namespace=\"singouins\",pod_name=~\"^sep-backend.*\",container_name!=\"\"})*100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"proto-api\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "App Commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "singouins_info{app=\"proto-api\"}",
     "legendFormat": "{{ commit }}"
    }
   ]
  },
  {
   "title": "App version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "singouins_info{app=\"proto-api\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "request /s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\",method=~\"GET|POST|DELETE\",app=\"proto-api\"}[30s])",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "request /m" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{app=\"proto-api\"}[1m])",
     "legendFormat": "{{ method }} HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "errors /s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!~\"200|201\"}[30s]))",
     "legendFormat": "status!=200"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "requests /s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"GET\",app=\"proto-api\"}[30s]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"POST\",app=\"proto-api\"}[30s]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"DELETE\",app=\"proto-api\"}[30s]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Requests response time [30s]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\",app=\"proto-api\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\",app=\"proto-api\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests under 500ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.5\",app=\"proto-api\"}[30s]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\",app=\"proto-api\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration (p50)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\",app=\"proto-api\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration (p90)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\",app=\"proto-api\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}