apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-prod
  name: redis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-api # For promtail logging
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
      labels:
        name: redis-api # For promtail logging
    spec:

      containers:
      - name: redis-api
        image: lordslair/redis-rest-api:1.2.1
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
        env:
        #  Flask variables
        - name: FLASK_DEBUG
          value: 'False'
        - name: CODE_ENOTFOUND
          value: '200'
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: redis-api-secret
              key: redis-api-token
        # Redis variables
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-host
        # Python env vars
        - name: PYTHONUNBUFFERED
          value: 'True'
        - name: PYTHONIOENCODING
          value: 'UTF-8'
        # Loguru env vars
        - name: LOGURU_FORMAT
          value: '<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>level={level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
        - name: LOGURU_COLORIZE
          value: 'true'
        - name: LOGURU_DEBUG_COLOR
          value: '<cyan><bold>'
        - name: LOGURU_LEVEL
          value: 'TRACE'
        # Other env vars
        - name: TZ
          value: 'Europe/Paris'
        # Network
        ports:
        - name: redis-api
          containerPort: 5000
        # Healthcheck
        livenessProbe:
            httpGet:
              path: /check
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 60
---
apiVersion: v1
kind: Service

metadata:
  namespace: singouins-prod
  name: redis-api-svc
spec:
  selector:
    name: redis-api # For promtail logging
  ports:
  - name: redis-api
    protocol: TCP
    port: 5000
    targetPort: 5000
