apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-grafana
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      tier: sep-backend
  template:
    metadata:
      labels:
        app: grafana
        tier: sep-backend
    spec:

      containers:
        - name: sep-backend-grafana
          image: grafana/grafana:8.3.3
          resources:
            limits:
              memory: 128Mi
              cpu: 50m
            requests:
              memory: 32Mi
              cpu: 10m
