apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-grafana
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana # For promtail logging
      tier: sep-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
        prometheus.io/path: "/metrics"
      labels:
        name: grafana # For promtail logging
        tier: sep-backend
    spec:

      containers:
        - name: sep-backend-grafana
          image: grafana/grafana:9.5.2
          resources:
            limits:
              memory: 128Mi
              cpu: 50m
            requests:
              memory: 32Mi
              cpu: 10m
          env:
            - name: GF_DATABASE_TYPE
              valueFrom:
                secretKeyRef:
                  name: sep-backend-grafana-secret
                  key: grafana-db-type
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: mariadb-host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: mariadb-port
            - name: GF_DATABASE_HOST
              value: "$(DATABASE_HOST):$(DATABASE_PORT)"
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sep-backend-grafana-secret
                  key: grafana-db-user
            - name: GF_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: sep-backend-grafana-secret
                  key: grafana-db-base
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sep-backend-grafana-secret
                  key: grafana-db-pass
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: sep-backend-grafana-secret
                  key: grafana-admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sep-backend-grafana-secret
                  key: grafana-admin-pass
        - name: sep-backend-mysqld-exporter
          image: prom/mysqld-exporter:v0.14.0
          resources:
            limits:
              memory: 32Mi
              cpu: 50m
            requests:
              memory: 16Mi
              cpu: 10m
          env:
            - name: DATA_SOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: mariadb-host
            - name: DATA_SOURCE_PORT
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: mariadb-port
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: mariadb-exporter-user
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: mariadb-exporter-pass
            - name: DATA_SOURCE_NAME
              value: '$(DATA_SOURCE_USER):$(DATA_SOURCE_PASS)@($(DATA_SOURCE_HOST):$(DATA_SOURCE_PORT))/'
          ports:
          - containerPort: 9104
