apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-backend
  name: wikijs-secret
type: Opaque
stringData:
  wikijs-db-base: 'singouins-wikijs'
  wikijs-db-host: 'mariadb-svc.singouins-databases'
  wikijs-db-pass: '<wikijs-db-pass>'
  wikijs-db-port: '3306'
  wikijs-db-user: 'singouins-wikijs'
  wikijs-db-type: 'mysql'
  wikijs-ssl: 'false'
  wikijs-ha: 'false'
  wikijs-git-user: '<wikijs-git-user>'
  wikijs-git-token: '<wikijs-git-token>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-backend
  name: discord-secret
type: Opaque
stringData:
  discord-admin-role: 'Team'
  discord-guild-id: '<discord-guild-id>'
  discord-token-babi: '<discord-token-babi>'
  discord-token-hapi: '<discord-token-hapi>'
  discord-invite-url: '<discord-invite-url>'
  discord-mongodb-host: '<discord-mongodb-host>'
  discord-mongodb-pass: '<discord-mongodb-pass>'
  discord-mongodb-user: 'singouins'
  discord-ssl-target-host: 'api.singouins.com'
  discord-ssl-channel: 'singouins-team'
  discord-k8s-namespaces: 'default,singouins-prod,singouins-dev,singouins-backend'