apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-phpmyadmin-svc
  labels:
    tier: sep-backend
spec:
  selector:
    name: phpmyadmin # For promtail logging
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 80
