apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-resolver
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resolver # For promtail logging
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "5000"
      labels:
        name: resolver # For promtail logging
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-resolver
        image: singouins/resolver:latest
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        env:
        # Node env vars
        - name: NODE_ENV
          value: 'dev'
        # App env vars
        - name: SEP_INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-internal-token
        - name: SEP_API_URL
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-url
        # Network
        ports:
        - name: resolver
          containerPort: 3000
        # Healthcheck
        livenessProbe:
            httpGet:
              path: /check
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
