apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-resolver-svc
  labels:
    tier: sep-backend
spec:
  selector:
    name: resolver # For promtail logging
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 3000
    name: resolver
