apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: singouins-monitoring
  name: loki-pvc
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
