apiVersion: v1
kind: ConfigMap

metadata:
  namespace: singouins
  name: sep-backend-discord-k8s
  labels:
    tier: sep-backend
data:
  kubeconfig-tea : |
    apiVersion: v1
    ...
  kubeconfig-ufp : |
    apiVersion: v1
    ...
