apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-discord
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: discord # For promtail logging
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        name: discord # For promtail logging
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-discord-commands
        image: singouins/discord:latest
        imagePullPolicy: Always
        command: ["/code/commands.py"]
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 50m
        volumeMounts:
        - name: kubeconfig-tea
          mountPath: /etc/k8s/dev
        - name: kubeconfig-ufp
          mountPath: /etc/k8s/prod
        env:
        # Discord env vars
        - name: SEP_DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-token-babi
        # Commented for production use
        #- name: SEP_DISCORD_GUILD
        #  valueFrom:
        #    secretKeyRef:
        #      name: sep-backend-discord-secret
        #      key: discord-guild-id
        # App env vars
        - name: SEP_INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-internal-token
        # Assets variables
        - name: SEP_URL_ASSETS
          valueFrom:
            secretKeyRef:
              name: sep-backend-git-secret
              key: git-assets-pages
        # Redis variables
        - name: SEP_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: sep-backend-redis-secret
              key: redis-base
        # Other env vars
        - name: LOGURU_LEVEL
          value: 'DEBUG'
        - name: TZ
          value: 'Europe/Paris'

      - name: sep-backend-discord-tasks
        image: singouins/discord:latest
        imagePullPolicy: Always
        command: ["/code/tasks.py"]
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
        # Discord env vars
        - name: SEP_DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-token-babi
        - name: SEP_DISCORD_GUILD
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-guild-id
        # SSL Validator env vars
        - name: SEP_SSL_TARGET_HOST
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-ssl-target-host
        - name: SEP_SSL_TARGET_PORT
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-ssl-target-port
        - name: SEP_SSL_CHANNEL
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-ssl-channel
        - name: SEP_SSL_IMG_URL
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-ssl-img-url
        # App env vars
        - name: SEP_INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-internal-token
        # Assets variables
        - name: SEP_URL_ASSETS
          valueFrom:
            secretKeyRef:
              name: sep-backend-git-secret
              key: git-assets-pages
        # Redis variables
        - name: SEP_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: sep-backend-redis-secret
              key: redis-base
        # Other env vars
        - name: LOGURU_LEVEL
          value: 'DEBUG'
        - name: TZ
          value: 'Europe/Paris'

      - name: sep-backend-discord-exporter
        image: lordslair/discord-prometheus-exporter:1.3.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 32Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
        # Discord env vars
        - name: EXPORTER_PORT
          value: '8080'
        - name: POLLING_INTERVAL
          value: '10'
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: discord-token-hapi
        # Other env vars
        - name: LOGURU_LEVEL
          value: 'DEBUG'
        - name: TZ
          value: 'Europe/Paris'

      volumes:
      - name: kubeconfig-tea
        configMap:
          name: sep-backend-discord-k8s
          items:
          - key: kubeconfig-tea
            path: kubeconfig.yaml
      - name: kubeconfig-ufp
        configMap:
          name: sep-backend-discord-k8s
          items:
          - key: kubeconfig-ufp
            path: kubeconfig.yaml
