apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-discord
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-discord-babi
        image: singouins/discord:latest
        imagePullPolicy: Always
        command: ["/code/babi.py"]
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
        # Discord env vars
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: token-babi
        # App env vars
        - name: SEP_API_URL
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-url
        - name: SEP_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: admin-token
        # PCS variables
        - name: SEP_PCS_URL
          valueFrom:
            secretKeyRef:
              name: sep-backend-pcs-secret
              key: pcs-url-public
        # Redis variables
        - name: SEP_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: sep-backend-redis-secret
              key: redis-base
        # Other env vars
        - name: PYTHONUNBUFFERED
          value: 'True'
        - name: PYTHONIOENCODING
          value: 'UTF-8'

      - name: sep-backend-discord-hapi
        image: singouins/discord:latest
        imagePullPolicy: Always
        command: ["/code/hapi.py"]
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
        # Discord env vars
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: token-hapi
        # App env vars
        - name: SEP_API_URL
          valueFrom:
            secretKeyRef:
              name: sep-backend-api-secret
              key: api-url # PROD url
        - name: SEP_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: admin-token
        # PCS variables
        - name: SEP_PCS_URL
          valueFrom:
            secretKeyRef:
              name: sep-backend-pcs-secret
              key: pcs-url-public
        # Redis variables
        - name: SEP_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: sep-backend-redis-secret
              key: redis-base
        # Other env vars
        - name: PYTHONUNBUFFERED
          value: 'True'
        - name: PYTHONIOENCODING
          value: 'UTF-8'
