apiVersion: v1
kind: ConfigMap

metadata:
  namespace: singouins
  name: sep-backend-deployer
data:
  deployer-sh : |
    #!/bin/sh
    FULLPATH="${CUST_OUTPUT_PATH}/${CUST_OUTPUT_FOLDER}"
    GIT_BIN=`which git`

    printf "\e[94m"
    printf "level=debug | git_binary:%s\n" "${GIT_BIN}"
    printf "level=debug | git_branch:%s\n" "${CUST_GIT_BRANCH}"
    printf "level=debug | git_user:%s\n" "${CUST_GIT_USER}"
    printf "level=debug | git_repo:%s/%s.git\n" "${CUST_GIT_REPO}"
    printf "level=debug | output_folder:%s\n" "${CUST_OUTPUT_FOLDER}"
    printf "level=debug | output_path:%s\n" "${CUST_OUTPUT_PATH}"
    printf "level=debug | output_quiet:%s\n" "${CUST_GIT_QUIET}"
    printf 'level=debug | -----\e[0m\n'

    # We check existence of the node user
    # As we will need it to run git commands (for file permissins)
    if getent passwd node > /dev/null;
    then
      printf "\e[94mlevel=debug | User:node exists\e[0m\n"
    else
      if adduser -h "${CUST_OUTPUT_FOLDER}" -u 1000 -D -H node;
      then
        printf "level=info  | User:node creation [\e[92m✓\e[0m]\n"
      else
        printf "level=error | User:node creation [\e[91m✗\e[0m]\n"
      fi
    fi

    if [ -d "${CUST_OUTPUT_PATH}" ]
    then
      # The BASE folder exists
      if [ -d "${FULLPATH}" ]
      then
        # The FULL folder exists == the branch was already cloned
        # We just need to `git pull`
        if su node -c "cd ${FULLPATH} && ${GIT_BIN} pull ${CUST_GIT_QUIET}";
        then
          printf "level=info  | Pulling [\e[92m✓\e[0m]\n"
        else
          printf "level=error | Pulling [\e[91m✗\e[0m]\n"
        fi
      else
        # The FULL folder do not exists == the branch was not cloned yet
        # We just need to `git clone`
        if su node -c "
            ${GIT_BIN} clone \
            ${CUST_GIT_QUIET} \
            --branch ${CUST_GIT_BRANCH} \
            --single-branch \
            https://${CUST_GIT_USER}:${CUST_GIT_TOKEN}@github.com/${CUST_GIT_REPO}.git \
            ${FULLPATH}
            ";
        then
          printf "level=info  | Cloning [\e[92m✓\e[0m]\n"
        else
          printf "level=error | Cloning [\e[91m✗\e[0m]\n"
        fi
      fi
    else
      # The BASE folder does not exist
      printf "level=error | Cloning not performed (FULLPATH not found)\n"
    fi
    printf "level=info  | We're done\n"
