apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: singouins-networking
  name: nginx-www-pvc
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: singouins-networking
  name: certbot-www-pvc
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: singouins-networking
  name: certbot-certs-pvc
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}