apiVersion: v1
kind: ConfigMap

metadata:
  namespace: singouins
  name: sep-backend-nginx
  labels:
    tier: sep-backend
data:
  htpasswd : |
    user1:$2y$11$BCRYPT HASHED PASSWORD
    user2:$2y$11$BCRYPT HASHED PASSWORD
  config : |

    #
    # http {}
    #

    log_format maxlog         '$proxy_protocol_addr - $remote_user [$time_local] '
                              '"$request" $status $body_bytes_sent '
                              '"$http_referer" "$http_user_agent" "$host"';

    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       1440m;
    ssl_session_tickets       off;

    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;

    # Mandatory for wss
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    #
    # <nginx-exporter>
    #

    server {
      listen      8080;

      location /stub_status {
          stub_status;
          allow 127.0.0.1;
          deny all;
      }
    }

    #
    # Default server
    #
    server {
      listen        80  default_server proxy_protocol;
      access_log    off;
      error_log     off;
      log_not_found off;
      deny          all;

    }
