apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-nginx
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx # For promtail logging
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
      labels:
        name: nginx # For promtail logging
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-nginx
        image: nginx:1.24-alpine
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: htpasswd
          mountPath: /etc/nginx/htpasswd
        - name: www
          mountPath: /var/www/certbot
        - name: certs
          mountPath: /etc/letsencrypt
        - name: websites
          mountPath: /var/www/websites

      - name: sep-backend-nginx-certbot
        image: certbot/certbot
        resources:
          limits:
            memory: 128Mi
            cpu: 50m
          requests:
            memory: 16Mi
            cpu: 10m
        command: ["/bin/sh"]
        args: ["-c", "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"]
        volumeMounts:
         - name: www
           mountPath: /var/www/certbot
         - name: certs
           mountPath: /etc/letsencrypt

      - name: sep-backend-nginx-deployer
        image: alpine/git:2.36.2
        # Here we don't launch crond by default
        # As production container DOES NOT launch automatic code pull
        #command: ["crond"]
        #args: ["-f", "-l", "2"]
        command: ["/bin/sh"]
        args: ["-c", "while :; do sleep 12h; done;"]
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 16Mi
            cpu: 50m
        env:
          - name: GIT_BRANCH
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-build-branch
          - name: GIT_QUIET
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-quiet
          - name: GIT_REPO
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-repo
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-user
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-token
          - name: OUTPUT_PATH
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-output-path
          - name: OUTPUT_FOLDER
            valueFrom:
              secretKeyRef:
                name: sep-backend-git-secret
                key: git-angular-output-folder
        volumeMounts:
        - name: websites
          mountPath: /var/www/websites
        - name: deployer-sh
          mountPath: /etc/periodic/daily

      - name: sep-backend-nginx-exporter
        image: nginx/nginx-prometheus-exporter
        resources:
          limits:
            memory: 32Mi
            cpu: 50m
          requests:
            memory: 16Mi
            cpu: 10m

      volumes:
      - name: config
        configMap:
          name: sep-backend-nginx
          items:
          - key: config
            path: site.conf
      - name: htpasswd
        configMap:
          name: sep-backend-nginx
          items:
          - key: htpasswd
            path: htpasswd
      - name: deployer-sh
        configMap:
          name: sep-backend-deployer
          items:
          - key: deployer-sh
            path: cron-deployer-sh
            mode: 0755
      - name: certs
        persistentVolumeClaim:
          claimName: sep-backend-certbot-certs
      - name: www
        persistentVolumeClaim:
          claimName: sep-backend-certbot-www
      - name: websites
        persistentVolumeClaim:
          claimName: sep-backend-code-websites
