apiVersion: v1
kind: Service

metadata:
  namespace: singouins-networking
  name: loadbalancer-svc
  annotations:
    service.beta.kubernetes.io/ovh-loadbalancer-proxy-protocol: "v2"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    name: nginx # For promtail logging
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
