apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-networking
  name: git-secret
type: Opaque
stringData:
  git-angular-quiet: '--quiet'
  git-angular-repo: '<git-angular-repo>'
  git-angular-token: '<git-angular-token>'
  git-angular-user: '<git-angular-user>'
  git-angular-output-path: '<git-angular-output-path>'
  git-angular-output-folder: '<git-angular-output-folder>'
  git-assets-repo: 'singouins/assets'
  git-assets-url: 'https://github.com/singouins/assets'
  git-assets-pages: 'https://singouins.github.io/assets'