apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-angular-prod
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
      tier: sep-backend
  template:
    metadata:
      labels:
        app: angular
        tier: sep-backend
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nodepool-b9ea22df-ec7f-4761-bc-node-fe0e74

      containers:
      - name: sep-backend-angular-prod
        image: singouins/ng-cli:12
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1024Mi
            cpu: 1000m
          requests:
            memory: 128Mi
            cpu: 50m
        env:
          - name: BUILD_TYPE
            value: 'production'
          - name: GIT_REPO
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: gitrepo
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: gituser
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: gittoken
          - name: QUIET
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: quiet
          - name: OUTPUT_PATH
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: outputpath
          - name: OUTPUT_FOLDER
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: outputfolder
        volumeMounts:
         - name: websites
           mountPath: /websites

      volumes:
      - name: websites
        persistentVolumeClaim:
          claimName: sep-backend-code-websites
