apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-ws-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: ws-proto
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 5000
