apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: mariadb-secret
type: Opaque
stringData:
  mariadb-root-password: '<mariadb-root-password>'
  mariadb-host: 'mariadb-svc'
  mariadb-port: '3306'
  mariadb-exporter-user: 'exporter'
  mariadb-exporter-pass: '<mariadb-exporter-pass>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: backup-secret
type: Opaque
stringData:
  backup-log-date: 'False'
  backup-log-info: 'True'
  backup-mysql-dump: 'True'
  backup-mysql-dblist: 'singouins-grafana,singouins-wikijs'
  backup-mysql-user: 'singouins-backup'
  backup-mysql-pass: '<backup-mysql-pass>'
  backup-mongodb-dump: 'True'
  backup-mongodb-export: 'True'
  backup-mongodb-host: '<backup-mongodb-host>'
  backup-mongodb-dblist: 'singouins,singouins-dev'
  backup-mongodb-user: 'singouins-backup'
  backup-mongodb-pass: '<backup-mongodb-pass>'
  backup-remote-path: 'backups-k8s/Singouins/PROD'
  backup-remote-s3-access-key: '<backup-remote-s3-access-key>'
  backup-remote-s3-secret-key: '<backup-remote-s3-secret-key>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-host: '<mongodb-host>'
  mongodb-port: '27017'
  mongodb-exporter-user: 'mongodb-exporter'
  mongodb-exporter-pass: '<mongodb-exporter-pass>'
  mongodb-exporter-uri: 'mongodb://mongodb-exporter:<mongodb-exporter-pass>@<mongodb-host>:27017'
  mongodb-uri: 'mongodb+srv://singouins:<mongodb-pass>@<mongodb-hosts>/singouins?authSource=admin&replicaSet=replicaset'