apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: mariadb-secret
type: Opaque
stringData:
  mariadb-root-password: '<mariadb-root-password>'
  mariadb-host: 'mariadb-svc'
  mariadb-port: '3306'
  mariadb-exporter-user: 'exporter'
  mariadb-exporter-pass: '<mariadb-exporter-pass>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: backup-secret
type: Opaque
stringData:
  backup-log-date: 'False'
  backup-log-info: 'True'
  backup-mysql-dump: 'True'
  backup-mysql-dblist: 'singouins-grafana,singouins-wikijs'
  backup-mysql-user: 'singouins-backup'
  backup-mysql-pass: '<backup-mysql-pass>'
  backup-mongodb-dump: 'True'
  backup-mongodb-export: 'True'
  backup-mongodb-host: '<backup-mongodb-host>'
  backup-mongodb-dblist: 'singouins,singouins-dev'
  backup-mongodb-user: 'singouins-backup'
  backup-mongodb-pass: '<backup-mongodb-pass>'
  backup-pcs-env-auth: 'false'
  backup-pcs-dir: '<backup-pcs-dir>'
  backup-redis-dump: 'True'
  backup-sqlite-dump: 'False'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: pcs-secret
type: Opaque
stringData:
  pcs-auth: 'https://auth.cloud.ovh.net/v3/'
  pcs-auth-version: '3'
  pcs-domain: 'default'
  pcs-private-user: '<pcs-private-user>'
  pcs-private-key: '<pcs-private-key>'
  pcs-public-url: '<pcs-public-url>'
  pcs-region: '<pcs-region>'
  pcs-tenant: '<pcs-tenant>'
  pcs-tenant-domain: 'default'
  pcs-type: swift
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: redis-secret
type: Opaque
stringData:
  redis-host: 'redis-svc'
  redis-port: '6379'
  redis-base: '0'
  redis-label: 'PROD'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-databases
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-uri: 'mongodb+srv://<mongodb-uri>'