apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-databases
  name: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-commander # For promtail logging
  template:
    metadata:
      labels:
        name: redis-commander # For promtail logging
    spec:

      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
        - name: REDIS_HOST
          value: 'redis-svc.singouins-databases'
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_BASE
          value: '0'
        - name: REDIS_LABEL
          value: 'REDIS'
        # Network
        ports:
        - name: redis-commander
          containerPort: 8081
        # Healthcheck
        livenessProbe:
            httpGet:
              path: /favicon.png
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service

metadata:
  namespace: singouins-databases
  name: redis-commander-svc
spec:
  selector:
    name: redis-commander # For promtail logging
  ports:
  - name: redis-commander
    protocol: TCP
    port: 8081
    targetPort: 8081