{
 "title": "App | Flask (API) Dashboard",
 "tags": [
  "Flask",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "query": "DEV : singouins-dev, PROD : singouins-prod"
   },
   { "name": "api", "query": "FrontAPI : api" }
  ]
 },
 "panels": [
  {
   "title": "MEM / CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"${env}\", container=\"${api}\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"${env}\", container=\"${api}\"} > 0) by (container)",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "MEM %Limit",
   "type": "gauge",
   "description": "API MEM Usage / API MEM Limit",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"${env}\", container=\"${api}\"} / container_spec_memory_limit_bytes{namespace=\"${env}\", container=\"${api}\"}) by (container) *100"
    }
   ]
  },
  {
   "title": "CPU %Limit",
   "type": "gauge",
   "description": "API CPU Usage / K8s API CPU Limit",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"${env}\", container=\"${api}\"}[5m])) by (container, pod) /\nsum(container_spec_cpu_quota{image!=\"\", namespace=\"${env}\", container=\"${api}\"}/container_spec_cpu_period{image!=\"\", namespace=\"${env}\", container=\"${api}\"}) by (container, pod)) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${env}\", container=\"${api}\"}[30s])) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"${env}\", container=\"${api}\"} / container_spec_cpu_period{namespace=\"${env}\", container=\"${api}\"}) by (container)",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\",method=~\"GET|POST|DELETE\",name=\"${api}\",kubernetes_namespace=\"${env}\"}[$__rate_interval])",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{name=\"${api}\",kubernetes_namespace=\"${env}\"}[1m])",
     "legendFormat": "{{ method }} HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!~\"200|201\",name=\"${api}\",kubernetes_namespace=\"${env}\"}[30s]))",
     "legendFormat": "status!=200"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"GET\",name=\"${api}\",kubernetes_namespace=\"${env}\"}[30s]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"POST\",name=\"api\"}[30s]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"DELETE\",name=\"api\"}[30s]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Requests response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\",name=\"${api}\",kubernetes_namespace=\"${env}\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\",name=\"${api}\",kubernetes_namespace=\"${env}\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\",name=\"${api}\",kubernetes_namespace=\"${env}\"}[300s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}