{
 "title": "App | Nginx Dashboard",
 "tags": [
  "Prometheus",
  "Nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_up{kubernetes_namespace=\"singouins\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{name=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{name=\"nginx\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{name=\"nginx\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{name=\"nginx\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{name=\"nginx\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{name=\"nginx\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{name=\"nginx\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{name=\"nginx\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}