apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-ws
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ws
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "5000"
      labels:
        name: ws
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-ws
        image: singouins/ws:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 50m
        # Network
        ports:
        - name: websocket
          containerPort: 5000
        env:
        # WebSocket env vars
        #- name: SEP_WSS_HOST
        #  value: '0.0.0.0'
        #- name: SEP_WSS_PORT
        #  value: '5000'
        # App variables
        - name: SEP_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: sep-backend-redis-secret
              key: redis-base
        - name: SEP_REDIS_SLEEP
          value: '1.0'
        # Python env vars
        - name: PYTHONUNBUFFERED
          value: 'True'
        # Healthcheck
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 60
