apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-ws-svc
spec:
  selector:
    name: ws
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: websocket
