apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: singouins-databases
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      restartPolicy: Always

      containers:
      - name: adminer
        image: adminer:4.8.1
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
        env:
        # ADMINER env vars
        - name: ADMINER_DEFAULT_SERVER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-host
---
apiVersion: v1
kind: Service
metadata:
  namespace: singouins-databases
  name: adminer-svc
spec:
  selector:
    app: adminer
  ports:
  - protocol: TCP
    port: 8080
