apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-dev
  name: resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resolver # For promtail logging
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "5000"
      labels:
        name: resolver # For promtail logging
    spec:
      restartPolicy: Always

      containers:
      - name: resolver
        image: singouins/resolver:attack-algo
        command: ["/bin/sh"]
        args: ["-c", "while :; do sleep 12h; done;"]
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        env:
        # MongoDB variables
        - name: MONGO_BASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-base
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-host
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-pass
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-user
        # Node env vars
        - name: NODE_ENV
          value: 'dev'
        # App variables
        - name: SEP_API_URL
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-external-url
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-internal-host
        - name: API_PORT
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-internal-port
        # Network
        ports:
        - name: resolver
          containerPort: 3000
        # Healthcheck
        #livenessProbe:
        #    httpGet:
        #      path: /check
        #      port: 3000
        #    initialDelaySeconds: 10
        #    timeoutSeconds: 5
---
apiVersion: v1
kind: Service

metadata:
  namespace: singouins-dev
  name: resolver-svc
spec:
  selector:
    name: resolver # For promtail logging
  ports:
  - name: resolver
    protocol: TCP
    port: 3000