apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-wikijs-svc
  labels:
    tier: sep-backend
spec:
  selector:
    name: wikijs
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: default
