apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-monitoring
  name: grafana-secret
type: Opaque
stringData:
  grafana-admin-user: '<grafana-admin-user>'
  grafana-admin-pass: '<grafana-admin-user>'
  grafana-yidhra-pass: '<grafana-admin-user>'
  grafana-db-base:    '<grafana-db-base>'
  grafana-db-host:    'mariadb-svc.singouins-databases'
  grafana-db-pass:    '<grafana-db-pass>'
  grafana-db-port:    '3306'
  grafana-db-user:    '<grafana-db-user>'
  grafana-db-type:    'mysql'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-monitoring
  name: prometheus-secret
type: Opaque
stringData:
  prometheus-retention-size: '5GB'