---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sep-backend-promtail
  namespace: singouins
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: promtail # For promtail logging
      tier: sep-backend
  template:
    metadata:
      labels:
        name: promtail # For promtail logging
        tier: sep-backend
    spec:
      serviceAccount: promtail-serviceaccount
      serviceAccountName: promtail-serviceaccount

      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        - -client.url=http://sep-backend-loki-svc:3100/api/prom/push
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: grafana/promtail:2.8.2
        imagePullPolicy: Always
        name: sep-backend-promtail
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 32Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 10
        ports:
        - containerPort: 9080
          name: http-metrics
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/promtail
          name: promtail-config
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true

      tolerations:
      - effect: NoSchedule
        operator: Exists

      volumes:
      - configMap:
          name: sep-backend-promtail-configmap
        name: promtail-config
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
---
