apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: singouins-databases
  name: redis-pvc
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
