apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis # For promtail logging
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        name: redis # For promtail logging
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-redis
        image: redis/redis-stack:6.2.6-v7
        command: ["redis-server", "/etc/redis/redis.conf"]
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 50m
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: db
          mountPath: /data
        - mountPath: /etc/redis
          name: config
      - name: sep-backend-redis-exporter
        image: oliver006/redis_exporter:v1.50.0-alpine
        resources:
          limits:
            memory: 32Mi
            cpu: 10m
          requests:
            memory: 16Mi
            cpu: 10m
        ports:
        - containerPort: 9121

      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: sep-backend-redis-db
      - name: config
        configMap:
          name: sep-backend-redis-conf
          items:
          - key: redis-conf
            path: redis.conf
