apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-backend
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wikijs # For promtail logging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: wikijs # For promtail logging
    spec:

      containers:
      - name: wikijs
        image: requarks/wiki:2.5
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 64Mi
            cpu: 10m
        ports:
          - containerPort: 3000
        env:
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-db-type
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-db-pass
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-db-base
        - name: SSL_ACTIVE
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-ssl
        - name: HA_ACTIVE
          valueFrom:
            secretKeyRef:
              name: wikijs-secret
              key: wikijs-ha
---
apiVersion: v1
kind: Service

metadata:
  namespace: singouins-backend
  name: wikijs-svc
spec:
  selector:
    name: wikijs
  ports:
  - name: wikijs-http
    protocol: TCP
    port: 3000
    targetPort: 3000
    