apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-dev
  name: api-secret
type: Opaque
stringData:
  api-external-url: 'https://api.singouins.com'
  api-internal-host: 'api-svc.singouins-dev'
  api-internal-port: '5000'
  api-jwt-secret: '<api-jwt-secret>'
  discord-invite-url: 'https://discord.gg/<invite-code>'
---  
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-dev
  name: smtp-secret
type: Opaque
stringData:
  smtp-from: '<smtp-from>'
  smtp-server: '<smtp-server>'
  smtp-user: '<smtp-user>'
  smtp-pass: '<smtp-pass>'
  smtp-host: '<smtp-host>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-dev
  name: resolver-secret
type: Opaque
stringData:
  resolver-host: 'resolver-svc'
  resolver-port: '5000'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins-dev
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-base: '<mongodb-base>'
  mongodb-host: '<mongodb-host>'
  mongodb-pass: '<mongodb-pass>'
  mongodb-user: '<mongodb-user>'